language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
addons:
    postgresql: "9.4"
env:
    - BABBAGE_TEST_DB=postgresql://postgres@/babbage
install:
    - python -m pip install -e .
    - python -m pip install psycopg2 nose flask-testing coverage
    - python -m pip install python-dateutil coveralls unicodecsv
before_script:
    - psql -c 'create database babbage;' -U postgres
    - python -m nose --version
script:
    - python -m nose --with-coverage --cover-package=babbage
after_success:
    - coveralls
