language: python
python:
    - "2.7"
    - "3.6"
addons:
    postgresql: "9.4"
env:
    global:
        - BABBAGE_TEST_DB=postgresql://postgres@/babbage
    matrix:
        - TOXENV="py${PYTHON_VERSION//./}"

install:
    - pip install tox coveralls
before_script:
    - psql -c 'create database babbage;' -U postgres
script:
    - tox
after_success:
    - coveralls
